---
title: Mark On Product
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    description: 
    image: 
    readtime: 
    is_post: true
- scope:
    path: ''
    type: pages
  values:
    description: 
    image: 
    is_page: true
markdown: kramdown
rouge: true
permalink: "/:title"
tagline: Product Management In The Real World
description: Product Management is a whole lot more than simply writing requirements.
  It's a combination of leadership, technology, design, and strategy. Mark On Product
  is a collection of articles covering these topics and much more.
url: https://markonproduct.com
author:
  name: Mark Mitchell
  twitter: markmitchell
  url: https://twitter.com/markmitchell
  bio: |-
    I started in the music business in New York City. Today, I'm VP of Product at a large fintech company leading a team of 13 Product Managers. I live in Atlanta with my wonderful wife and our three children. Like many Product Managers, I too traveled an unusual path to get here. <a href="/about-mark-mitchell">Here’s the full scoop</a>.
    <br>
    <br>
    I’d like to hear from you. Feel free to  <a href="/contact">send me a note</a>, or let's connect on <a href="https://twitter.com/MarkMitchell">Twitter</a> or <a href="https://www.linkedin.com/in/markreidmitchell/">LinkedIn</a>.
  image: v1533636293/post-images/mark-mitchell-bio-photo.jpg
paginate: 12
version: 2.1.5
github:
  repo: https://github.com/markthelefty/markthelefty.github.io
plugins:
- jekyll-sitemap
